/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConfirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost200,
  ConfirmResponse,
  FilterStatsResponse,
  FilteredContentListResponse,
  FilteredContentResponse,
  GetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetParams,
  HTTPValidationError,
  RestoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost200,
  RestoreResponse
} from '.././schemas';

import { apiClient } from '../../client';




/**
 * Get all filtered content for a meeting.

Args:
    meeting_id: Meeting ID
    include_restored: If True, include content that was restored (default: False)

Returns:
    List of filtered content items
 * @summary Get Filtered Content
 */
export const getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet = (
    meetingId: string,
    params?: GetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<FilteredContentListResponse>(
      {url: `/api/v1/filters/meetings/${meetingId}/filtered`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetQueryKey = (meetingId: string,
    params?: GetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetParams,) => {
    return [
    `/api/v1/filters/meetings/${meetingId}/filtered`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetQueryOptions = <TData = Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>, TError = HTTPValidationError>(meetingId: string,
    params?: GetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetQueryKey(meetingId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>> = ({ signal }) => getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet(meetingId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>>
export type GetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetQueryError = HTTPValidationError


export function useGetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet<TData = Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params: undefined |  GetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>,
          TError,
          Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet<TData = Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: GetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>,
          TError,
          Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet<TData = Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: GetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Filtered Content
 */

export function useGetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet<TData = Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: GetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFilteredContentApiV1FiltersMeetingsMeetingIdFilteredGetQueryOptions(meetingId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get statistics about filtered content for a meeting.
 * @summary Get Filter Stats
 */
export const getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<FilterStatsResponse>(
      {url: `/api/v1/filters/meetings/${meetingId}/filtered/stats`, method: 'GET', signal
    },
      );
    }
  



export const getGetFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGetQueryKey = (meetingId: string,) => {
    return [
    `/api/v1/filters/meetings/${meetingId}/filtered/stats`
    ] as const;
    }

    
export const getGetFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGetQueryOptions = <TData = Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>, TError = HTTPValidationError>(meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGetQueryKey(meetingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>> = ({ signal }) => getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet(meetingId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>>
export type GetFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGetQueryError = HTTPValidationError


export function useGetFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet<TData = Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>, TError = HTTPValidationError>(
 meetingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet<TData = Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet<TData = Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Filter Stats
 */

export function useGetFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet<TData = Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFilterStatsApiV1FiltersMeetingsMeetingIdFilteredStatsGetQueryOptions(meetingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Restore all filtered content for a meeting.
 * @summary Restore All Filtered Content
 */
export const restoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<RestoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost200>(
      {url: `/api/v1/filters/meetings/${meetingId}/filtered/restore-all`, method: 'POST', signal
    },
      );
    }
  


export const getRestoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost>>, TError,{meetingId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof restoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost>>, TError,{meetingId: string}, TContext> => {

const mutationKey = ['restoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost>>, {meetingId: string}> = (props) => {
          const {meetingId} = props ?? {};

          return  restoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost(meetingId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RestoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPostMutationResult = NonNullable<Awaited<ReturnType<typeof restoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost>>>
    
    export type RestoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPostMutationError = HTTPValidationError

    /**
 * @summary Restore All Filtered Content
 */
export const useRestoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost>>, TError,{meetingId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPost>>,
        TError,
        {meetingId: string},
        TContext
      > => {
      return useMutation(getRestoreAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredRestoreAllPostMutationOptions(options), queryClient);
    }
    /**
 * Confirm all non-restored filtered content as casual talk.
 * @summary Confirm All Filtered Content
 */
export const confirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ConfirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost200>(
      {url: `/api/v1/filters/meetings/${meetingId}/filtered/confirm-all`, method: 'POST', signal
    },
      );
    }
  


export const getConfirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost>>, TError,{meetingId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof confirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost>>, TError,{meetingId: string}, TContext> => {

const mutationKey = ['confirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost>>, {meetingId: string}> = (props) => {
          const {meetingId} = props ?? {};

          return  confirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost(meetingId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPostMutationResult = NonNullable<Awaited<ReturnType<typeof confirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost>>>
    
    export type ConfirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPostMutationError = HTTPValidationError

    /**
 * @summary Confirm All Filtered Content
 */
export const useConfirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost>>, TError,{meetingId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPost>>,
        TError,
        {meetingId: string},
        TContext
      > => {
      return useMutation(getConfirmAllFilteredContentApiV1FiltersMeetingsMeetingIdFilteredConfirmAllPostMutationOptions(options), queryClient);
    }
    /**
 * Get a specific filtered content item.
 * @summary Get Filtered Content By Id
 */
export const getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet = (
    meetingId: string,
    contentId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<FilteredContentResponse>(
      {url: `/api/v1/filters/meetings/${meetingId}/filtered/${contentId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGetQueryKey = (meetingId: string,
    contentId: string,) => {
    return [
    `/api/v1/filters/meetings/${meetingId}/filtered/${contentId}`
    ] as const;
    }

    
export const getGetFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>, TError = HTTPValidationError>(meetingId: string,
    contentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGetQueryKey(meetingId,contentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>> = ({ signal }) => getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet(meetingId,contentId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId && contentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>>
export type GetFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGetQueryError = HTTPValidationError


export function useGetFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet<TData = Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>, TError = HTTPValidationError>(
 meetingId: string,
    contentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet<TData = Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>, TError = HTTPValidationError>(
 meetingId: string,
    contentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet<TData = Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>, TError = HTTPValidationError>(
 meetingId: string,
    contentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Filtered Content By Id
 */

export function useGetFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet<TData = Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>, TError = HTTPValidationError>(
 meetingId: string,
    contentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFilteredContentByIdApiV1FiltersMeetingsMeetingIdFilteredContentIdGetQueryOptions(meetingId,contentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Restore filtered content back to the transcript.

This marks the content as restored, indicating the user
disagrees with the AI's classification.
 * @summary Restore Filtered Content
 */
export const restoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePost = (
    meetingId: string,
    contentId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<RestoreResponse>(
      {url: `/api/v1/filters/meetings/${meetingId}/filtered/${contentId}/restore`, method: 'POST', signal
    },
      );
    }
  


export const getRestoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePost>>, TError,{meetingId: string;contentId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof restoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePost>>, TError,{meetingId: string;contentId: string}, TContext> => {

const mutationKey = ['restoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePost>>, {meetingId: string;contentId: string}> = (props) => {
          const {meetingId,contentId} = props ?? {};

          return  restoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePost(meetingId,contentId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RestoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePostMutationResult = NonNullable<Awaited<ReturnType<typeof restoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePost>>>
    
    export type RestoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePostMutationError = HTTPValidationError

    /**
 * @summary Restore Filtered Content
 */
export const useRestoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePost>>, TError,{meetingId: string;contentId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePost>>,
        TError,
        {meetingId: string;contentId: string},
        TContext
      > => {
      return useMutation(getRestoreFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdRestorePostMutationOptions(options), queryClient);
    }
    /**
 * Undo a restore action - mark content as filtered again.
 * @summary Undo Restore
 */
export const undoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDelete = (
    meetingId: string,
    contentId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<RestoreResponse>(
      {url: `/api/v1/filters/meetings/${meetingId}/filtered/${contentId}/restore`, method: 'DELETE', signal
    },
      );
    }
  


export const getUndoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof undoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDelete>>, TError,{meetingId: string;contentId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof undoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDelete>>, TError,{meetingId: string;contentId: string}, TContext> => {

const mutationKey = ['undoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof undoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDelete>>, {meetingId: string;contentId: string}> = (props) => {
          const {meetingId,contentId} = props ?? {};

          return  undoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDelete(meetingId,contentId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UndoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof undoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDelete>>>
    
    export type UndoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDeleteMutationError = HTTPValidationError

    /**
 * @summary Undo Restore
 */
export const useUndoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof undoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDelete>>, TError,{meetingId: string;contentId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof undoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDelete>>,
        TError,
        {meetingId: string;contentId: string},
        TContext
      > => {
      return useMutation(getUndoRestoreApiV1FiltersMeetingsMeetingIdFilteredContentIdRestoreDeleteMutationOptions(options), queryClient);
    }
    /**
 * Confirm that filtered content is indeed casual talk.

This is used for AI learning - confirmed items can be used
to improve future filtering accuracy.
 * @summary Confirm Filtered Content
 */
export const confirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPost = (
    meetingId: string,
    contentId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ConfirmResponse>(
      {url: `/api/v1/filters/meetings/${meetingId}/filtered/${contentId}/confirm`, method: 'POST', signal
    },
      );
    }
  


export const getConfirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPost>>, TError,{meetingId: string;contentId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof confirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPost>>, TError,{meetingId: string;contentId: string}, TContext> => {

const mutationKey = ['confirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPost>>, {meetingId: string;contentId: string}> = (props) => {
          const {meetingId,contentId} = props ?? {};

          return  confirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPost(meetingId,contentId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPostMutationResult = NonNullable<Awaited<ReturnType<typeof confirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPost>>>
    
    export type ConfirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPostMutationError = HTTPValidationError

    /**
 * @summary Confirm Filtered Content
 */
export const useConfirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPost>>, TError,{meetingId: string;contentId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPost>>,
        TError,
        {meetingId: string;contentId: string},
        TContext
      > => {
      return useMutation(getConfirmFilteredContentApiV1FiltersMeetingsMeetingIdFilteredContentIdConfirmPostMutationOptions(options), queryClient);
    }
    