/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMeetingProgressApiV1MeetingsMeetingIdProgressGet200,
  HTTPValidationError,
  ListMeetingsApiV1MeetingsGetParams,
  MeetingCreate,
  MeetingResponse,
  MeetingStatusUpdate,
  MeetingWithDetails
} from '.././schemas';

import { apiClient } from '../../client';




/**
 * List meetings with optional filters.
 * @summary List Meetings
 */
export const listMeetingsApiV1MeetingsGet = (
    params?: ListMeetingsApiV1MeetingsGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MeetingResponse[]>(
      {url: `/api/v1/meetings`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListMeetingsApiV1MeetingsGetQueryKey = (params?: ListMeetingsApiV1MeetingsGetParams,) => {
    return [
    `/api/v1/meetings`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListMeetingsApiV1MeetingsGetQueryOptions = <TData = Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>, TError = HTTPValidationError>(params?: ListMeetingsApiV1MeetingsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMeetingsApiV1MeetingsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>> = ({ signal }) => listMeetingsApiV1MeetingsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMeetingsApiV1MeetingsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>>
export type ListMeetingsApiV1MeetingsGetQueryError = HTTPValidationError


export function useListMeetingsApiV1MeetingsGet<TData = Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListMeetingsApiV1MeetingsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>,
          TError,
          Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMeetingsApiV1MeetingsGet<TData = Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>, TError = HTTPValidationError>(
 params?: ListMeetingsApiV1MeetingsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>,
          TError,
          Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMeetingsApiV1MeetingsGet<TData = Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>, TError = HTTPValidationError>(
 params?: ListMeetingsApiV1MeetingsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Meetings
 */

export function useListMeetingsApiV1MeetingsGet<TData = Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>, TError = HTTPValidationError>(
 params?: ListMeetingsApiV1MeetingsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMeetingsApiV1MeetingsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMeetingsApiV1MeetingsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new meeting.
 * @summary Create Meeting
 */
export const createMeetingApiV1MeetingsPost = (
    meetingCreate: MeetingCreate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MeetingResponse>(
      {url: `/api/v1/meetings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: meetingCreate, signal
    },
      );
    }
  


export const getCreateMeetingApiV1MeetingsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMeetingApiV1MeetingsPost>>, TError,{data: MeetingCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createMeetingApiV1MeetingsPost>>, TError,{data: MeetingCreate}, TContext> => {

const mutationKey = ['createMeetingApiV1MeetingsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMeetingApiV1MeetingsPost>>, {data: MeetingCreate}> = (props) => {
          const {data} = props ?? {};

          return  createMeetingApiV1MeetingsPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMeetingApiV1MeetingsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createMeetingApiV1MeetingsPost>>>
    export type CreateMeetingApiV1MeetingsPostMutationBody = MeetingCreate
    export type CreateMeetingApiV1MeetingsPostMutationError = HTTPValidationError

    /**
 * @summary Create Meeting
 */
export const useCreateMeetingApiV1MeetingsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMeetingApiV1MeetingsPost>>, TError,{data: MeetingCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMeetingApiV1MeetingsPost>>,
        TError,
        {data: MeetingCreate},
        TContext
      > => {
      return useMutation(getCreateMeetingApiV1MeetingsPostMutationOptions(options), queryClient);
    }
    /**
 * Get a meeting by ID with all related data.
 * @summary Get Meeting
 */
export const getMeetingApiV1MeetingsMeetingIdGet = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MeetingWithDetails>(
      {url: `/api/v1/meetings/${meetingId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetMeetingApiV1MeetingsMeetingIdGetQueryKey = (meetingId: string,) => {
    return [
    `/api/v1/meetings/${meetingId}`
    ] as const;
    }

    
export const getGetMeetingApiV1MeetingsMeetingIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>, TError = HTTPValidationError>(meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeetingApiV1MeetingsMeetingIdGetQueryKey(meetingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>> = ({ signal }) => getMeetingApiV1MeetingsMeetingIdGet(meetingId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeetingApiV1MeetingsMeetingIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>>
export type GetMeetingApiV1MeetingsMeetingIdGetQueryError = HTTPValidationError


export function useGetMeetingApiV1MeetingsMeetingIdGet<TData = Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>, TError = HTTPValidationError>(
 meetingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingApiV1MeetingsMeetingIdGet<TData = Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingApiV1MeetingsMeetingIdGet<TData = Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Meeting
 */

export function useGetMeetingApiV1MeetingsMeetingIdGet<TData = Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingApiV1MeetingsMeetingIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeetingApiV1MeetingsMeetingIdGetQueryOptions(meetingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Delete a meeting and all related data.
 * @summary Delete Meeting
 */
export const deleteMeetingApiV1MeetingsMeetingIdDelete = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/meetings/${meetingId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteMeetingApiV1MeetingsMeetingIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMeetingApiV1MeetingsMeetingIdDelete>>, TError,{meetingId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteMeetingApiV1MeetingsMeetingIdDelete>>, TError,{meetingId: string}, TContext> => {

const mutationKey = ['deleteMeetingApiV1MeetingsMeetingIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMeetingApiV1MeetingsMeetingIdDelete>>, {meetingId: string}> = (props) => {
          const {meetingId} = props ?? {};

          return  deleteMeetingApiV1MeetingsMeetingIdDelete(meetingId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMeetingApiV1MeetingsMeetingIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMeetingApiV1MeetingsMeetingIdDelete>>>
    
    export type DeleteMeetingApiV1MeetingsMeetingIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Meeting
 */
export const useDeleteMeetingApiV1MeetingsMeetingIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMeetingApiV1MeetingsMeetingIdDelete>>, TError,{meetingId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMeetingApiV1MeetingsMeetingIdDelete>>,
        TError,
        {meetingId: string},
        TContext
      > => {
      return useMutation(getDeleteMeetingApiV1MeetingsMeetingIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Update meeting status.
 * @summary Update Meeting Status
 */
export const updateMeetingStatusApiV1MeetingsMeetingIdStatusPatch = (
    meetingId: string,
    meetingStatusUpdate: MeetingStatusUpdate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MeetingResponse>(
      {url: `/api/v1/meetings/${meetingId}/status`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: meetingStatusUpdate, signal
    },
      );
    }
  


export const getUpdateMeetingStatusApiV1MeetingsMeetingIdStatusPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMeetingStatusApiV1MeetingsMeetingIdStatusPatch>>, TError,{meetingId: string;data: MeetingStatusUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMeetingStatusApiV1MeetingsMeetingIdStatusPatch>>, TError,{meetingId: string;data: MeetingStatusUpdate}, TContext> => {

const mutationKey = ['updateMeetingStatusApiV1MeetingsMeetingIdStatusPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMeetingStatusApiV1MeetingsMeetingIdStatusPatch>>, {meetingId: string;data: MeetingStatusUpdate}> = (props) => {
          const {meetingId,data} = props ?? {};

          return  updateMeetingStatusApiV1MeetingsMeetingIdStatusPatch(meetingId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMeetingStatusApiV1MeetingsMeetingIdStatusPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateMeetingStatusApiV1MeetingsMeetingIdStatusPatch>>>
    export type UpdateMeetingStatusApiV1MeetingsMeetingIdStatusPatchMutationBody = MeetingStatusUpdate
    export type UpdateMeetingStatusApiV1MeetingsMeetingIdStatusPatchMutationError = HTTPValidationError

    /**
 * @summary Update Meeting Status
 */
export const useUpdateMeetingStatusApiV1MeetingsMeetingIdStatusPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMeetingStatusApiV1MeetingsMeetingIdStatusPatch>>, TError,{meetingId: string;data: MeetingStatusUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMeetingStatusApiV1MeetingsMeetingIdStatusPatch>>,
        TError,
        {meetingId: string;data: MeetingStatusUpdate},
        TContext
      > => {
      return useMutation(getUpdateMeetingStatusApiV1MeetingsMeetingIdStatusPatchMutationOptions(options), queryClient);
    }
    /**
 * Get meeting processing progress for polling.
 * @summary Get Meeting Progress
 */
export const getMeetingProgressApiV1MeetingsMeetingIdProgressGet = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GetMeetingProgressApiV1MeetingsMeetingIdProgressGet200>(
      {url: `/api/v1/meetings/${meetingId}/progress`, method: 'GET', signal
    },
      );
    }
  



export const getGetMeetingProgressApiV1MeetingsMeetingIdProgressGetQueryKey = (meetingId: string,) => {
    return [
    `/api/v1/meetings/${meetingId}/progress`
    ] as const;
    }

    
export const getGetMeetingProgressApiV1MeetingsMeetingIdProgressGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>, TError = HTTPValidationError>(meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeetingProgressApiV1MeetingsMeetingIdProgressGetQueryKey(meetingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>> = ({ signal }) => getMeetingProgressApiV1MeetingsMeetingIdProgressGet(meetingId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeetingProgressApiV1MeetingsMeetingIdProgressGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>>
export type GetMeetingProgressApiV1MeetingsMeetingIdProgressGetQueryError = HTTPValidationError


export function useGetMeetingProgressApiV1MeetingsMeetingIdProgressGet<TData = Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>, TError = HTTPValidationError>(
 meetingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingProgressApiV1MeetingsMeetingIdProgressGet<TData = Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingProgressApiV1MeetingsMeetingIdProgressGet<TData = Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Meeting Progress
 */

export function useGetMeetingProgressApiV1MeetingsMeetingIdProgressGet<TData = Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1MeetingsMeetingIdProgressGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeetingProgressApiV1MeetingsMeetingIdProgressGetQueryOptions(meetingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




