/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for a single agenda item in general meetings.
 */
export interface AgendaItem {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  description?: string | null;
  presenter?: string | null;
  duration_minutes?: number | null;
}
