/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Single correction item.
 */
export interface CorrectionItemResponse {
  original: string;
  corrected: string;
  category: string;
}
