/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { FilterStatsResponseByReason } from './filterStatsResponseByReason';

/**
 * Statistics about filtered content for a meeting.
 */
export interface FilterStatsResponse {
  meeting_id: string;
  total_filtered: number;
  by_reason: FilterStatsResponseByReason;
  restored_count: number;
  confirmed_count: number;
  average_confidence: number | null;
}
