/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Filtered content response.
 */
export interface FilteredContentResponse {
  id: string;
  meeting_id: string;
  content: string;
  filter_reason: string;
  confidence: number | null;
  is_restored: boolean;
  is_confirmed: boolean;
  speaker_label: string | null;
  speaker_name: string | null;
  start_time: number | null;
  end_time: number | null;
  created_at: string;
}
