/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { FilteredContentResponse } from './filteredContentResponse';

/**
 * List response for filtered contents.
 */
export interface FilteredContentListResponse {
  meeting_id: string;
  items: FilteredContentResponse[];
  total_count: number;
  restored_count: number;
  confirmed_count: number;
}
