/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { MeetingStatus } from './meetingStatus';

export type ListMeetingsApiV1MeetingsGetParams = {
team_id?: string | null;
status?: MeetingStatus | null;
from_date?: string | null;
to_date?: string | null;
};
