/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { VocabularyCategory } from './vocabularyCategory';

export type ListVocabularyApiV1TeamsTeamIdVocabularyGetParams = {
/**
 * Filter by category
 */
category?: VocabularyCategory | null;
/**
 * Search in term or correction
 */
search?: string | null;
};
