/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for meeting minutes info in meeting response.
 */
export interface MeetingMinutesInfo {
  id: string;
  ai_model: string;
  is_edited: boolean;
  created_at: string;
}
