/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Meeting type enum - P2 feature.
 */
export type MeetingType = typeof MeetingType[keyof typeof MeetingType];


export const MeetingType = {
  weekly_report: 'weekly_report',
  general: 'general',
} as const;
