/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { MeetingStatus } from './meetingStatus';

/**
 * Schema for meeting response.
 */
export interface MeetingResponse {
  created_at: string;
  updated_at: string;
  id: string;
  team_id: string;
  meeting_date: string;
  title: string;
  status: MeetingStatus;
  meeting_mode: string;
  error_message: string | null;
  confluence_page_id: string | null;
  confluence_page_url: string | null;
}
