/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { AgendaItem } from './agendaItem';

/**
 * Schema for updating a meeting.
 */
export interface MeetingUpdate {
  title?: string | null;
  meeting_date?: string | null;
  agenda_items?: AgendaItem[] | null;
}
