/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Meeting status enum.
 */
export type MeetingStatus = typeof MeetingStatus[keyof typeof MeetingStatus];


export const MeetingStatus = {
  created: 'created',
  weekly_report_loaded: 'weekly_report_loaded',
  preparing: 'preparing',
  in_progress: 'in_progress',
  recording_done: 'recording_done',
  recording_uploaded: 'recording_uploaded',
  transcribing: 'transcribing',
  transcribed: 'transcribed',
  generating_minutes: 'generating_minutes',
  draft_ready: 'draft_ready',
  published: 'published',
  failed: 'failed',
} as const;
