/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { MeetingStatus } from './meetingStatus';

/**
 * Schema for updating meeting status.
 */
export interface MeetingStatusUpdate {
  status: MeetingStatus;
  error_message?: string | null;
}
