/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to update meeting progress.
 */
export interface MeetingProgressUpdate {
  current_speaker_index: number;
  current_item_index: number;
}
