/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { AgendaItem } from './agendaItem';
import type { MeetingMode } from './meetingMode';
import type { MeetingType } from './meetingType';

/**
 * Schema for creating a meeting.
 */
export interface MeetingCreate {
  team_id: string;
  meeting_date: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  meeting_mode?: MeetingMode;
  meeting_type?: MeetingType;
  agenda_items?: AgendaItem[] | null;
}
