/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { AgendaItem } from './agendaItem';
import type { MeetingMinutesInfo } from './meetingMinutesInfo';
import type { MeetingStatus } from './meetingStatus';
import type { RecordingInfo } from './recordingInfo';
import type { WeeklyReportInfo } from './weeklyReportInfo';

/**
 * Schema for meeting with all related data.
 */
export interface MeetingWithDetails {
  created_at: string;
  updated_at: string;
  id: string;
  team_id: string;
  meeting_date: string;
  title: string;
  location: string | null;
  status: MeetingStatus;
  meeting_mode: string;
  meeting_type: string;
  error_message: string | null;
  confluence_page_id: string | null;
  confluence_page_url: string | null;
  agenda_items: AgendaItem[] | null;
  context_terms: string[] | null;
  context_instructions: string | null;
  recording: RecordingInfo | null;
  weekly_report: WeeklyReportInfo | null;
  minutes: MeetingMinutesInfo | null;
}
