/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Meeting mode enum.
 */
export type MeetingMode = typeof MeetingMode[keyof typeof MeetingMode];


export const MeetingMode = {
  upload: 'upload',
  realtime: 'realtime',
} as const;
