/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { MeetingStartResponseQuestionTree } from './meetingStartResponseQuestionTree';

/**
 * Response after starting a realtime meeting.
 */
export interface MeetingStartResponse {
  meeting_id: string;
  status: string;
  question_tree: MeetingStartResponseQuestionTree;
}
