/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { MeetingProgressResponseQuestionTree } from './meetingProgressResponseQuestionTree';

/**
 * Response with current meeting progress.
 */
export interface MeetingProgressResponse {
  meeting_id: string;
  status: string;
  current_speaker_index: number | null;
  current_item_index: number | null;
  question_tree: MeetingProgressResponseQuestionTree;
}
