/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status response for minutes generation.
 */
export interface MinutesGenerationStatusResponse {
  meeting_id: string;
  status: string;
  has_minutes: boolean;
  error_message: string | null;
}
