/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Meeting minutes response.
 */
export interface MinutesResponse {
  id: string;
  meeting_id: string;
  content_markdown: string;
  ai_model: string;
  prompt_version: string;
  is_edited: boolean;
  edited_content: string | null;
}
