/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Recording response model.
 */
export interface RecordingResponse {
  id: string;
  meeting_id: string;
  original_filename: string;
  stored_filename: string;
  file_size: number;
  mime_type: string;
  duration_seconds: number | null;
}
