/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for recording info in meeting response.
 */
export interface RecordingInfo {
  id: string;
  original_filename: string;
  file_size: number;
  duration_seconds: number | null;
}
