/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response after restoring filtered content.
 */
export interface RestoreResponse {
  id: string;
  meeting_id: string;
  is_restored: boolean;
  message: string;
}
