/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { ServiceStatusStatus } from './serviceStatusStatus';

/**
 * Individual service health status.
 */
export interface ServiceStatus {
  status: ServiceStatusStatus;
  latency_ms?: number | null;
  error?: string | null;
}
