/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

export type ServiceStatusStatus = typeof ServiceStatusStatus[keyof typeof ServiceStatusStatus];


export const ServiceStatusStatus = {
  healthy: 'healthy',
  unhealthy: 'unhealthy',
} as const;
