/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { TeamMemberResponse } from './teamMemberResponse';

/**
 * Schema for team with members.
 */
export interface TeamWithMembers {
  created_at: string;
  updated_at: string;
  id: string;
  name: string;
  members: TeamMemberResponse[];
}
