/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { TeamMemberCreate } from './teamMemberCreate';

/**
 * Schema for creating a team.
 */
export interface TeamCreate {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  password?: string | null;
  confluence_base_url?: string | null;
  confluence_space_key?: string | null;
  confluence_username?: string | null;
  confluence_token?: string | null;
  filtering_enabled?: boolean;
  /**
   * @minimum 0
   * @maximum 1
   */
  filtering_confidence_threshold?: number;
  members?: TeamMemberCreate[] | null;
}
