/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for team response (list view - no sensitive data).
 */
export interface TeamResponse {
  created_at: string;
  updated_at: string;
  id: string;
  name: string;
  has_password?: boolean;
}
