/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for creating a team member.
 */
export interface TeamMemberCreate {
  /**
   * @minLength 1
   * @maxLength 50
   */
  name: string;
  /** @minimum 1 */
  presentation_order: number;
}
