/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for updating a team.
 */
export interface TeamUpdate {
  name?: string | null;
  password?: string | null;
  confluence_base_url?: string | null;
  confluence_space_key?: string | null;
  confluence_username?: string | null;
  confluence_token?: string | null;
  filtering_enabled?: boolean | null;
  filtering_confidence_threshold?: number | null;
}
