/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for updating a team.
 */
export interface TeamUpdate {
  name?: string | null;
  password?: string | null;
  confluence_base_url?: string | null;
  confluence_space_key?: string | null;
}
