/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for team member response.
 */
export interface TeamMemberResponse {
  created_at: string;
  updated_at: string;
  id: string;
  team_id: string;
  name: string;
  presentation_order: number;
  is_active: boolean;
}
