/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for updating a team member.
 */
export interface TeamMemberUpdate {
  name?: string | null;
  presentation_order?: number | null;
  is_active?: boolean | null;
}
