/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for transcription.
 */
export interface TranscriptionRequest {
  enable_chat_filter?: boolean;
}
