/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Transcript segment response.
 */
export interface TranscriptSegmentResponse {
  id: string;
  start_time: number;
  end_time: number;
  text: string;
  speaker_label: string | null;
  speaker_name: string | null;
  confidence: number | null;
}
