/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Transcription status response.
 */
export interface TranscriptionStatusResponse {
  meeting_id: string;
  status: string;
  segments_count: number;
  duration_seconds: number | null;
  error_message: string | null;
}
