/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { VocabularyCategory } from './vocabularyCategory';

/**
 * Schema for creating a vocabulary term.

term: 올바른 용어 (AI가 정확히 인식해야 할 단어)
correction: 비슷하게 들릴 수 있는 발음/표기 힌트 (선택, 미입력시 term과 동일)
 */
export interface VocabularyCreate {
  /**
   * 올바른 용어
   * @minLength 1
   * @maxLength 200
   */
  term: string;
  /** 발음 힌트 (선택) */
  correction?: string | null;
  category?: VocabularyCategory;
}
