/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { VocabularyCategory } from './vocabularyCategory';

/**
 * Schema for creating a vocabulary term.
 */
export interface VocabularyCreate {
  /**
   * @minLength 1
   * @maxLength 200
   */
  term: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  correction: string;
  category?: VocabularyCategory;
}
