/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { VocabularyCategory } from './vocabularyCategory';

/**
 * Schema for a single item in bulk import.
 */
export interface VocabularyBulkImportItem {
  /**
   * 올바른 용어
   * @minLength 1
   * @maxLength 200
   */
  term: string;
  /** 발음 힌트 (선택) */
  correction?: string | null;
  category?: VocabularyCategory;
}
