/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { VocabularyBulkImportItem } from './vocabularyBulkImportItem';

/**
 * Schema for bulk import request.
 */
export interface VocabularyBulkImport {
  /**
   * @minItems 1
   * @maxItems 500
   */
  items: VocabularyBulkImportItem[];
  skip_duplicates?: boolean;
}
