/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { VocabularyResponse } from './vocabularyResponse';

/**
 * Schema for bulk import response.
 */
export interface VocabularyBulkImportResponse {
  imported: number;
  skipped: number;
  items: VocabularyResponse[];
}
