/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { VocabularyCategory } from './vocabularyCategory';

/**
 * Schema for vocabulary response.
 */
export interface VocabularyResponse {
  created_at: string;
  updated_at: string;
  id: string;
  team_id: string;
  term: string;
  correction: string;
  category: VocabularyCategory;
}
