/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for weekly report info in meeting response.
 */
export interface WeeklyReportInfo {
  id: string;
  confluence_page_id: string;
  confluence_page_url: string;
}
