/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import type { WeeklyReportResponseParsedData } from './weeklyReportResponseParsedData';

/**
 * Response with loaded weekly report data.
 */
export interface WeeklyReportResponse {
  id: string;
  meeting_id: string;
  confluence_page_id: string;
  confluence_page_url: string;
  parsed_data: WeeklyReportResponseParsedData;
}
