/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to load a weekly report for a meeting.
 */
export interface WeeklyReportLoadRequest {
  confluence_page_id: string;
}
