/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet200,
  GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetParams,
  HTTPValidationError,
  TranscriptSegmentResponse,
  TranscriptionStatusResponse
} from '.././schemas';

import { apiClient } from '../../client';




/**
 * Start transcription processing for a meeting.

This endpoint triggers STT processing in the background.
Use GET /meetings/{meeting_id}/progress to poll for status.
 * @summary Start Transcription
 */
export const startTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePost = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<TranscriptionStatusResponse>(
      {url: `/api/v1/transcription/meetings/${meetingId}/transcribe`, method: 'POST', signal
    },
      );
    }
  


export const getStartTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePost>>, TError,{meetingId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePost>>, TError,{meetingId: string}, TContext> => {

const mutationKey = ['startTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePost>>, {meetingId: string}> = (props) => {
          const {meetingId} = props ?? {};

          return  startTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePost(meetingId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePostMutationResult = NonNullable<Awaited<ReturnType<typeof startTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePost>>>
    
    export type StartTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePostMutationError = HTTPValidationError

    /**
 * @summary Start Transcription
 */
export const useStartTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePost>>, TError,{meetingId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePost>>,
        TError,
        {meetingId: string},
        TContext
      > => {
      return useMutation(getStartTranscriptionApiV1TranscriptionMeetingsMeetingIdTranscribePostMutationOptions(options), queryClient);
    }
    /**
 * Get all transcript segments for a meeting.
 * @summary Get Meeting Transcripts
 */
export const getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<TranscriptSegmentResponse[]>(
      {url: `/api/v1/transcription/meetings/${meetingId}/transcripts`, method: 'GET', signal
    },
      );
    }
  



export const getGetMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGetQueryKey = (meetingId: string,) => {
    return [
    `/api/v1/transcription/meetings/${meetingId}/transcripts`
    ] as const;
    }

    
export const getGetMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>, TError = HTTPValidationError>(meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGetQueryKey(meetingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>> = ({ signal }) => getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet(meetingId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>>
export type GetMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGetQueryError = HTTPValidationError


export function useGetMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet<TData = Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>, TError = HTTPValidationError>(
 meetingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet<TData = Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet<TData = Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Meeting Transcripts
 */

export function useGetMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet<TData = Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeetingTranscriptsApiV1TranscriptionMeetingsMeetingIdTranscriptsGetQueryOptions(meetingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get full transcript as plain text.

Args:
    meeting_id: Meeting ID
    include_speakers: Include speaker labels in output
 * @summary Get Meeting Transcript Text
 */
export const getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet = (
    meetingId: string,
    params?: GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet200>(
      {url: `/api/v1/transcription/meetings/${meetingId}/transcripts/text`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetQueryKey = (meetingId: string,
    params?: GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetParams,) => {
    return [
    `/api/v1/transcription/meetings/${meetingId}/transcripts/text`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>, TError = HTTPValidationError>(meetingId: string,
    params?: GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetQueryKey(meetingId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>> = ({ signal }) => getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet(meetingId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>>
export type GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetQueryError = HTTPValidationError


export function useGetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet<TData = Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params: undefined |  GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet<TData = Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet<TData = Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Meeting Transcript Text
 */

export function useGetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet<TData = Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: GetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeetingTranscriptTextApiV1TranscriptionMeetingsMeetingIdTranscriptsTextGetQueryOptions(meetingId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




