/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  TeamCreate,
  TeamMemberCreate,
  TeamMemberResponse,
  TeamMemberUpdate,
  TeamResponse,
  TeamWithMembers
} from '.././schemas';

import { apiClient } from '../../client';




/**
 * List all teams.
 * @summary List Teams
 */
export const listTeamsApiV1TeamsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<TeamResponse[]>(
      {url: `/api/v1/teams`, method: 'GET', signal
    },
      );
    }
  



export const getListTeamsApiV1TeamsGetQueryKey = () => {
    return [
    `/api/v1/teams`
    ] as const;
    }

    
export const getListTeamsApiV1TeamsGetQueryOptions = <TData = Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTeamsApiV1TeamsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>> = ({ signal }) => listTeamsApiV1TeamsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTeamsApiV1TeamsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>>
export type ListTeamsApiV1TeamsGetQueryError = unknown


export function useListTeamsApiV1TeamsGet<TData = Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>,
          TError,
          Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamsApiV1TeamsGet<TData = Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>,
          TError,
          Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamsApiV1TeamsGet<TData = Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Teams
 */

export function useListTeamsApiV1TeamsGet<TData = Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamsApiV1TeamsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTeamsApiV1TeamsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new team with optional members.
 * @summary Create Team
 */
export const createTeamApiV1TeamsPost = (
    teamCreate: TeamCreate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<TeamWithMembers>(
      {url: `/api/v1/teams`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: teamCreate, signal
    },
      );
    }
  


export const getCreateTeamApiV1TeamsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTeamApiV1TeamsPost>>, TError,{data: TeamCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTeamApiV1TeamsPost>>, TError,{data: TeamCreate}, TContext> => {

const mutationKey = ['createTeamApiV1TeamsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTeamApiV1TeamsPost>>, {data: TeamCreate}> = (props) => {
          const {data} = props ?? {};

          return  createTeamApiV1TeamsPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTeamApiV1TeamsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createTeamApiV1TeamsPost>>>
    export type CreateTeamApiV1TeamsPostMutationBody = TeamCreate
    export type CreateTeamApiV1TeamsPostMutationError = HTTPValidationError

    /**
 * @summary Create Team
 */
export const useCreateTeamApiV1TeamsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTeamApiV1TeamsPost>>, TError,{data: TeamCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTeamApiV1TeamsPost>>,
        TError,
        {data: TeamCreate},
        TContext
      > => {
      return useMutation(getCreateTeamApiV1TeamsPostMutationOptions(options), queryClient);
    }
    /**
 * Get a team by ID with members.
 * @summary Get Team
 */
export const getTeamApiV1TeamsTeamIdGet = (
    teamId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<TeamWithMembers>(
      {url: `/api/v1/teams/${teamId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetTeamApiV1TeamsTeamIdGetQueryKey = (teamId: string,) => {
    return [
    `/api/v1/teams/${teamId}`
    ] as const;
    }

    
export const getGetTeamApiV1TeamsTeamIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTeamApiV1TeamsTeamIdGetQueryKey(teamId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>> = ({ signal }) => getTeamApiV1TeamsTeamIdGet(teamId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTeamApiV1TeamsTeamIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>>
export type GetTeamApiV1TeamsTeamIdGetQueryError = HTTPValidationError


export function useGetTeamApiV1TeamsTeamIdGet<TData = Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeamApiV1TeamsTeamIdGet<TData = Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeamApiV1TeamsTeamIdGet<TData = Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Team
 */

export function useGetTeamApiV1TeamsTeamIdGet<TData = Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamApiV1TeamsTeamIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTeamApiV1TeamsTeamIdGetQueryOptions(teamId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Delete a team.
 * @summary Delete Team
 */
export const deleteTeamApiV1TeamsTeamIdDelete = (
    teamId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/teams/${teamId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteTeamApiV1TeamsTeamIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTeamApiV1TeamsTeamIdDelete>>, TError,{teamId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTeamApiV1TeamsTeamIdDelete>>, TError,{teamId: string}, TContext> => {

const mutationKey = ['deleteTeamApiV1TeamsTeamIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTeamApiV1TeamsTeamIdDelete>>, {teamId: string}> = (props) => {
          const {teamId} = props ?? {};

          return  deleteTeamApiV1TeamsTeamIdDelete(teamId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTeamApiV1TeamsTeamIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTeamApiV1TeamsTeamIdDelete>>>
    
    export type DeleteTeamApiV1TeamsTeamIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Team
 */
export const useDeleteTeamApiV1TeamsTeamIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTeamApiV1TeamsTeamIdDelete>>, TError,{teamId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTeamApiV1TeamsTeamIdDelete>>,
        TError,
        {teamId: string},
        TContext
      > => {
      return useMutation(getDeleteTeamApiV1TeamsTeamIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * List all members of a team.
 * @summary List Team Members
 */
export const listTeamMembersApiV1TeamsTeamIdMembersGet = (
    teamId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<TeamMemberResponse[]>(
      {url: `/api/v1/teams/${teamId}/members`, method: 'GET', signal
    },
      );
    }
  



export const getListTeamMembersApiV1TeamsTeamIdMembersGetQueryKey = (teamId: string,) => {
    return [
    `/api/v1/teams/${teamId}/members`
    ] as const;
    }

    
export const getListTeamMembersApiV1TeamsTeamIdMembersGetQueryOptions = <TData = Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTeamMembersApiV1TeamsTeamIdMembersGetQueryKey(teamId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>> = ({ signal }) => listTeamMembersApiV1TeamsTeamIdMembersGet(teamId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTeamMembersApiV1TeamsTeamIdMembersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>>
export type ListTeamMembersApiV1TeamsTeamIdMembersGetQueryError = HTTPValidationError


export function useListTeamMembersApiV1TeamsTeamIdMembersGet<TData = Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>,
          TError,
          Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamMembersApiV1TeamsTeamIdMembersGet<TData = Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>,
          TError,
          Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamMembersApiV1TeamsTeamIdMembersGet<TData = Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Team Members
 */

export function useListTeamMembersApiV1TeamsTeamIdMembersGet<TData = Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamMembersApiV1TeamsTeamIdMembersGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTeamMembersApiV1TeamsTeamIdMembersGetQueryOptions(teamId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Add a member to a team.
 * @summary Add Team Member
 */
export const addTeamMemberApiV1TeamsTeamIdMembersPost = (
    teamId: string,
    teamMemberCreate: TeamMemberCreate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<TeamMemberResponse>(
      {url: `/api/v1/teams/${teamId}/members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: teamMemberCreate, signal
    },
      );
    }
  


export const getAddTeamMemberApiV1TeamsTeamIdMembersPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addTeamMemberApiV1TeamsTeamIdMembersPost>>, TError,{teamId: string;data: TeamMemberCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addTeamMemberApiV1TeamsTeamIdMembersPost>>, TError,{teamId: string;data: TeamMemberCreate}, TContext> => {

const mutationKey = ['addTeamMemberApiV1TeamsTeamIdMembersPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addTeamMemberApiV1TeamsTeamIdMembersPost>>, {teamId: string;data: TeamMemberCreate}> = (props) => {
          const {teamId,data} = props ?? {};

          return  addTeamMemberApiV1TeamsTeamIdMembersPost(teamId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddTeamMemberApiV1TeamsTeamIdMembersPostMutationResult = NonNullable<Awaited<ReturnType<typeof addTeamMemberApiV1TeamsTeamIdMembersPost>>>
    export type AddTeamMemberApiV1TeamsTeamIdMembersPostMutationBody = TeamMemberCreate
    export type AddTeamMemberApiV1TeamsTeamIdMembersPostMutationError = HTTPValidationError

    /**
 * @summary Add Team Member
 */
export const useAddTeamMemberApiV1TeamsTeamIdMembersPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addTeamMemberApiV1TeamsTeamIdMembersPost>>, TError,{teamId: string;data: TeamMemberCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addTeamMemberApiV1TeamsTeamIdMembersPost>>,
        TError,
        {teamId: string;data: TeamMemberCreate},
        TContext
      > => {
      return useMutation(getAddTeamMemberApiV1TeamsTeamIdMembersPostMutationOptions(options), queryClient);
    }
    /**
 * Update a team member.
 * @summary Update Team Member
 */
export const updateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatch = (
    teamId: string,
    memberId: string,
    teamMemberUpdate: TeamMemberUpdate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<TeamMemberResponse>(
      {url: `/api/v1/teams/${teamId}/members/${memberId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: teamMemberUpdate, signal
    },
      );
    }
  


export const getUpdateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatch>>, TError,{teamId: string;memberId: string;data: TeamMemberUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatch>>, TError,{teamId: string;memberId: string;data: TeamMemberUpdate}, TContext> => {

const mutationKey = ['updateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatch>>, {teamId: string;memberId: string;data: TeamMemberUpdate}> = (props) => {
          const {teamId,memberId,data} = props ?? {};

          return  updateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatch(teamId,memberId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatch>>>
    export type UpdateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatchMutationBody = TeamMemberUpdate
    export type UpdateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Team Member
 */
export const useUpdateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatch>>, TError,{teamId: string;memberId: string;data: TeamMemberUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatch>>,
        TError,
        {teamId: string;memberId: string;data: TeamMemberUpdate},
        TContext
      > => {
      return useMutation(getUpdateTeamMemberApiV1TeamsTeamIdMembersMemberIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Remove a member from a team.
 * @summary Remove Team Member
 */
export const removeTeamMemberApiV1TeamsTeamIdMembersMemberIdDelete = (
    teamId: string,
    memberId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/teams/${teamId}/members/${memberId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getRemoveTeamMemberApiV1TeamsTeamIdMembersMemberIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeTeamMemberApiV1TeamsTeamIdMembersMemberIdDelete>>, TError,{teamId: string;memberId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removeTeamMemberApiV1TeamsTeamIdMembersMemberIdDelete>>, TError,{teamId: string;memberId: string}, TContext> => {

const mutationKey = ['removeTeamMemberApiV1TeamsTeamIdMembersMemberIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeTeamMemberApiV1TeamsTeamIdMembersMemberIdDelete>>, {teamId: string;memberId: string}> = (props) => {
          const {teamId,memberId} = props ?? {};

          return  removeTeamMemberApiV1TeamsTeamIdMembersMemberIdDelete(teamId,memberId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveTeamMemberApiV1TeamsTeamIdMembersMemberIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeTeamMemberApiV1TeamsTeamIdMembersMemberIdDelete>>>
    
    export type RemoveTeamMemberApiV1TeamsTeamIdMembersMemberIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Remove Team Member
 */
export const useRemoveTeamMemberApiV1TeamsTeamIdMembersMemberIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeTeamMemberApiV1TeamsTeamIdMembersMemberIdDelete>>, TError,{teamId: string;memberId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeTeamMemberApiV1TeamsTeamIdMembersMemberIdDelete>>,
        TError,
        {teamId: string;memberId: string},
        TContext
      > => {
      return useMutation(getRemoveTeamMemberApiV1TeamsTeamIdMembersMemberIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Reorder team members by providing ordered list of member IDs.
 * @summary Reorder Team Members
 */
export const reorderTeamMembersApiV1TeamsTeamIdMembersReorderPost = (
    teamId: string,
    reorderTeamMembersApiV1TeamsTeamIdMembersReorderPostBody: string[],
 signal?: AbortSignal
) => {
      
      
      return apiClient<TeamMemberResponse[]>(
      {url: `/api/v1/teams/${teamId}/members/reorder`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reorderTeamMembersApiV1TeamsTeamIdMembersReorderPostBody, signal
    },
      );
    }
  


export const getReorderTeamMembersApiV1TeamsTeamIdMembersReorderPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderTeamMembersApiV1TeamsTeamIdMembersReorderPost>>, TError,{teamId: string;data: string[]}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof reorderTeamMembersApiV1TeamsTeamIdMembersReorderPost>>, TError,{teamId: string;data: string[]}, TContext> => {

const mutationKey = ['reorderTeamMembersApiV1TeamsTeamIdMembersReorderPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reorderTeamMembersApiV1TeamsTeamIdMembersReorderPost>>, {teamId: string;data: string[]}> = (props) => {
          const {teamId,data} = props ?? {};

          return  reorderTeamMembersApiV1TeamsTeamIdMembersReorderPost(teamId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ReorderTeamMembersApiV1TeamsTeamIdMembersReorderPostMutationResult = NonNullable<Awaited<ReturnType<typeof reorderTeamMembersApiV1TeamsTeamIdMembersReorderPost>>>
    export type ReorderTeamMembersApiV1TeamsTeamIdMembersReorderPostMutationBody = string[]
    export type ReorderTeamMembersApiV1TeamsTeamIdMembersReorderPostMutationError = HTTPValidationError

    /**
 * @summary Reorder Team Members
 */
export const useReorderTeamMembersApiV1TeamsTeamIdMembersReorderPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderTeamMembersApiV1TeamsTeamIdMembersReorderPost>>, TError,{teamId: string;data: string[]}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reorderTeamMembersApiV1TeamsTeamIdMembersReorderPost>>,
        TError,
        {teamId: string;data: string[]},
        TContext
      > => {
      return useMutation(getReorderTeamMembersApiV1TeamsTeamIdMembersReorderPostMutationOptions(options), queryClient);
    }
    