/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost,
  HTTPValidationError,
  RecordingResponse
} from '.././schemas';

import { apiClient } from '../../client';




/**
 * Upload a recording file for a meeting.

Max file size: 100MB
Supported formats: MP3, WAV, WebM, OGG, M4A, AAC, FLAC
 * @summary Upload Recording
 */
export const uploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost = (
    meetingId: string,
    bodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost: BodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost.file);
if(bodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost.source !== undefined) {
 formData.append(`source`, bodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost.source);
 }

      return apiClient<RecordingResponse>(
      {url: `/api/v1/recordings/meetings/${meetingId}/recording`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost>>, TError,{meetingId: string;data: BodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost>>, TError,{meetingId: string;data: BodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost}, TContext> => {

const mutationKey = ['uploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost>>, {meetingId: string;data: BodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost}> = (props) => {
          const {meetingId,data} = props ?? {};

          return  uploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost(meetingId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPostMutationResult = NonNullable<Awaited<ReturnType<typeof uploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost>>>
    export type UploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPostMutationBody = BodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost
    export type UploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPostMutationError = HTTPValidationError

    /**
 * @summary Upload Recording
 */
export const useUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost>>, TError,{meetingId: string;data: BodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost>>,
        TError,
        {meetingId: string;data: BodyUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPost},
        TContext
      > => {
      return useMutation(getUploadRecordingApiV1RecordingsMeetingsMeetingIdRecordingPostMutationOptions(options), queryClient);
    }
    /**
 * Get recording info for a meeting.
 * @summary Get Meeting Recording
 */
export const getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<RecordingResponse>(
      {url: `/api/v1/recordings/meetings/${meetingId}/recording`, method: 'GET', signal
    },
      );
    }
  



export const getGetMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGetQueryKey = (meetingId: string,) => {
    return [
    `/api/v1/recordings/meetings/${meetingId}/recording`
    ] as const;
    }

    
export const getGetMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>, TError = HTTPValidationError>(meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGetQueryKey(meetingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>> = ({ signal }) => getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet(meetingId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>>
export type GetMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGetQueryError = HTTPValidationError


export function useGetMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet<TData = Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>, TError = HTTPValidationError>(
 meetingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet<TData = Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet<TData = Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Meeting Recording
 */

export function useGetMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet<TData = Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingGetQueryOptions(meetingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Delete a recording from a meeting.
 * @summary Delete Meeting Recording
 */
export const deleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDelete = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/recordings/meetings/${meetingId}/recording`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDelete>>, TError,{meetingId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDelete>>, TError,{meetingId: string}, TContext> => {

const mutationKey = ['deleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDelete>>, {meetingId: string}> = (props) => {
          const {meetingId} = props ?? {};

          return  deleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDelete(meetingId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDelete>>>
    
    export type DeleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Meeting Recording
 */
export const useDeleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDelete>>, TError,{meetingId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDelete>>,
        TError,
        {meetingId: string},
        TContext
      > => {
      return useMutation(getDeleteMeetingRecordingApiV1RecordingsMeetingsMeetingIdRecordingDeleteMutationOptions(options), queryClient);
    }
    