/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet200,
  HTTPValidationError,
  MeetingEndResponse,
  MeetingProgressResponse,
  MeetingProgressUpdate,
  MeetingStartResponse
} from '.././schemas';

import { apiClient } from '../../client';




/**
 * Start a realtime meeting.

Generates question tree from weekly report and transitions to IN_PROGRESS.
 * @summary Start Realtime Meeting
 */
export const startRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPost = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MeetingStartResponse>(
      {url: `/api/v1/realtime/meetings/${meetingId}/start`, method: 'POST', signal
    },
      );
    }
  


export const getStartRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPost>>, TError,{meetingId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPost>>, TError,{meetingId: string}, TContext> => {

const mutationKey = ['startRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPost>>, {meetingId: string}> = (props) => {
          const {meetingId} = props ?? {};

          return  startRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPost(meetingId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPostMutationResult = NonNullable<Awaited<ReturnType<typeof startRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPost>>>
    
    export type StartRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPostMutationError = HTTPValidationError

    /**
 * @summary Start Realtime Meeting
 */
export const useStartRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPost>>, TError,{meetingId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPost>>,
        TError,
        {meetingId: string},
        TContext
      > => {
      return useMutation(getStartRealtimeMeetingApiV1RealtimeMeetingsMeetingIdStartPostMutationOptions(options), queryClient);
    }
    /**
 * Get current meeting progress (orchestration state).
 * @summary Get Meeting Progress
 */
export const getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MeetingProgressResponse>(
      {url: `/api/v1/realtime/meetings/${meetingId}/progress`, method: 'GET', signal
    },
      );
    }
  



export const getGetMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGetQueryKey = (meetingId: string,) => {
    return [
    `/api/v1/realtime/meetings/${meetingId}/progress`
    ] as const;
    }

    
export const getGetMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>, TError = HTTPValidationError>(meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGetQueryKey(meetingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>> = ({ signal }) => getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet(meetingId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>>
export type GetMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGetQueryError = HTTPValidationError


export function useGetMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet<TData = Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>, TError = HTTPValidationError>(
 meetingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet<TData = Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet<TData = Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Meeting Progress
 */

export function useGetMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet<TData = Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressGetQueryOptions(meetingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update meeting progress (current speaker/item).
 * @summary Update Meeting Progress
 */
export const updateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPut = (
    meetingId: string,
    meetingProgressUpdate: MeetingProgressUpdate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MeetingProgressResponse>(
      {url: `/api/v1/realtime/meetings/${meetingId}/progress`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: meetingProgressUpdate, signal
    },
      );
    }
  


export const getUpdateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPut>>, TError,{meetingId: string;data: MeetingProgressUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPut>>, TError,{meetingId: string;data: MeetingProgressUpdate}, TContext> => {

const mutationKey = ['updateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPut>>, {meetingId: string;data: MeetingProgressUpdate}> = (props) => {
          const {meetingId,data} = props ?? {};

          return  updateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPut(meetingId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPut>>>
    export type UpdateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPutMutationBody = MeetingProgressUpdate
    export type UpdateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPutMutationError = HTTPValidationError

    /**
 * @summary Update Meeting Progress
 */
export const useUpdateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPut>>, TError,{meetingId: string;data: MeetingProgressUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPut>>,
        TError,
        {meetingId: string;data: MeetingProgressUpdate},
        TContext
      > => {
      return useMutation(getUpdateMeetingProgressApiV1RealtimeMeetingsMeetingIdProgressPutMutationOptions(options), queryClient);
    }
    /**
 * Advance to the next question item.
 * @summary Advance To Next Item
 */
export const advanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPost = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MeetingProgressResponse>(
      {url: `/api/v1/realtime/meetings/${meetingId}/next-item`, method: 'POST', signal
    },
      );
    }
  


export const getAdvanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof advanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPost>>, TError,{meetingId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof advanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPost>>, TError,{meetingId: string}, TContext> => {

const mutationKey = ['advanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof advanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPost>>, {meetingId: string}> = (props) => {
          const {meetingId} = props ?? {};

          return  advanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPost(meetingId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdvanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPostMutationResult = NonNullable<Awaited<ReturnType<typeof advanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPost>>>
    
    export type AdvanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPostMutationError = HTTPValidationError

    /**
 * @summary Advance To Next Item
 */
export const useAdvanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof advanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPost>>, TError,{meetingId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof advanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPost>>,
        TError,
        {meetingId: string},
        TContext
      > => {
      return useMutation(getAdvanceToNextItemApiV1RealtimeMeetingsMeetingIdNextItemPostMutationOptions(options), queryClient);
    }
    /**
 * Advance to the next speaker.
 * @summary Advance To Next Speaker
 */
export const advanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPost = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MeetingProgressResponse>(
      {url: `/api/v1/realtime/meetings/${meetingId}/next-speaker`, method: 'POST', signal
    },
      );
    }
  


export const getAdvanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof advanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPost>>, TError,{meetingId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof advanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPost>>, TError,{meetingId: string}, TContext> => {

const mutationKey = ['advanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof advanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPost>>, {meetingId: string}> = (props) => {
          const {meetingId} = props ?? {};

          return  advanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPost(meetingId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AdvanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPostMutationResult = NonNullable<Awaited<ReturnType<typeof advanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPost>>>
    
    export type AdvanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPostMutationError = HTTPValidationError

    /**
 * @summary Advance To Next Speaker
 */
export const useAdvanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof advanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPost>>, TError,{meetingId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof advanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPost>>,
        TError,
        {meetingId: string},
        TContext
      > => {
      return useMutation(getAdvanceToNextSpeakerApiV1RealtimeMeetingsMeetingIdNextSpeakerPostMutationOptions(options), queryClient);
    }
    /**
 * End a realtime meeting.

Transitions to RECORDING_DONE, ready for recording upload and STT.
 * @summary End Realtime Meeting
 */
export const endRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPost = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MeetingEndResponse>(
      {url: `/api/v1/realtime/meetings/${meetingId}/end`, method: 'POST', signal
    },
      );
    }
  


export const getEndRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof endRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPost>>, TError,{meetingId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof endRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPost>>, TError,{meetingId: string}, TContext> => {

const mutationKey = ['endRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof endRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPost>>, {meetingId: string}> = (props) => {
          const {meetingId} = props ?? {};

          return  endRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPost(meetingId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EndRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPostMutationResult = NonNullable<Awaited<ReturnType<typeof endRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPost>>>
    
    export type EndRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPostMutationError = HTTPValidationError

    /**
 * @summary End Realtime Meeting
 */
export const useEndRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof endRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPost>>, TError,{meetingId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof endRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPost>>,
        TError,
        {meetingId: string},
        TContext
      > => {
      return useMutation(getEndRealtimeMeetingApiV1RealtimeMeetingsMeetingIdEndPostMutationOptions(options), queryClient);
    }
    /**
 * Get the question tree for a meeting.
 * @summary Get Question Tree
 */
export const getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet200>(
      {url: `/api/v1/realtime/meetings/${meetingId}/question-tree`, method: 'GET', signal
    },
      );
    }
  



export const getGetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGetQueryKey = (meetingId: string,) => {
    return [
    `/api/v1/realtime/meetings/${meetingId}/question-tree`
    ] as const;
    }

    
export const getGetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGetQueryOptions = <TData = Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>, TError = HTTPValidationError>(meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGetQueryKey(meetingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>> = ({ signal }) => getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet(meetingId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>>
export type GetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGetQueryError = HTTPValidationError


export function useGetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet<TData = Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>, TError = HTTPValidationError>(
 meetingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>,
          TError,
          Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet<TData = Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>,
          TError,
          Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet<TData = Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Question Tree
 */

export function useGetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet<TData = Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuestionTreeApiV1RealtimeMeetingsMeetingIdQuestionTreeGetQueryOptions(meetingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




