/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet200,
  ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetParams,
  HTTPValidationError,
  MinutesGenerationStatusResponse,
  MinutesResponse,
  MinutesUpdateRequest,
  PublishResponse
} from '.././schemas';

import { apiClient } from '../../client';




/**
 * Start meeting minutes generation.

Requires transcription to be completed first.
Uses GPT to generate minutes from transcript and weekly report.
 * @summary Start Minutes Generation
 */
export const startMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPost = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MinutesGenerationStatusResponse>(
      {url: `/api/v1/minutes/meetings/${meetingId}/generate-minutes`, method: 'POST', signal
    },
      );
    }
  


export const getStartMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPost>>, TError,{meetingId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPost>>, TError,{meetingId: string}, TContext> => {

const mutationKey = ['startMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPost>>, {meetingId: string}> = (props) => {
          const {meetingId} = props ?? {};

          return  startMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPost(meetingId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPostMutationResult = NonNullable<Awaited<ReturnType<typeof startMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPost>>>
    
    export type StartMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPostMutationError = HTTPValidationError

    /**
 * @summary Start Minutes Generation
 */
export const useStartMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPost>>, TError,{meetingId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPost>>,
        TError,
        {meetingId: string},
        TContext
      > => {
      return useMutation(getStartMinutesGenerationApiV1MinutesMeetingsMeetingIdGenerateMinutesPostMutationOptions(options), queryClient);
    }
    /**
 * Get meeting minutes.
 * @summary Get Meeting Minutes
 */
export const getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MinutesResponse>(
      {url: `/api/v1/minutes/meetings/${meetingId}/minutes`, method: 'GET', signal
    },
      );
    }
  



export const getGetMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGetQueryKey = (meetingId: string,) => {
    return [
    `/api/v1/minutes/meetings/${meetingId}/minutes`
    ] as const;
    }

    
export const getGetMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>, TError = HTTPValidationError>(meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGetQueryKey(meetingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>> = ({ signal }) => getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet(meetingId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>>
export type GetMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGetQueryError = HTTPValidationError


export function useGetMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet<TData = Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>, TError = HTTPValidationError>(
 meetingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet<TData = Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet<TData = Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Meeting Minutes
 */

export function useGetMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet<TData = Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesGetQueryOptions(meetingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update meeting minutes content.

Stores the edited version and marks as edited.
 * @summary Update Meeting Minutes
 */
export const updateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPut = (
    meetingId: string,
    minutesUpdateRequest: MinutesUpdateRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<MinutesResponse>(
      {url: `/api/v1/minutes/meetings/${meetingId}/minutes`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: minutesUpdateRequest, signal
    },
      );
    }
  


export const getUpdateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPut>>, TError,{meetingId: string;data: MinutesUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPut>>, TError,{meetingId: string;data: MinutesUpdateRequest}, TContext> => {

const mutationKey = ['updateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPut>>, {meetingId: string;data: MinutesUpdateRequest}> = (props) => {
          const {meetingId,data} = props ?? {};

          return  updateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPut(meetingId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPut>>>
    export type UpdateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPutMutationBody = MinutesUpdateRequest
    export type UpdateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPutMutationError = HTTPValidationError

    /**
 * @summary Update Meeting Minutes
 */
export const useUpdateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPut>>, TError,{meetingId: string;data: MinutesUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPut>>,
        TError,
        {meetingId: string;data: MinutesUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateMeetingMinutesApiV1MinutesMeetingsMeetingIdMinutesPutMutationOptions(options), queryClient);
    }
    /**
 * Publish meeting minutes to Confluence.

Creates a new Confluence page with the minutes content.
Uses team-specific Confluence settings if available.
 * @summary Publish Minutes To Confluence
 */
export const publishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPost = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<PublishResponse>(
      {url: `/api/v1/minutes/meetings/${meetingId}/publish`, method: 'POST', signal
    },
      );
    }
  


export const getPublishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPost>>, TError,{meetingId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof publishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPost>>, TError,{meetingId: string}, TContext> => {

const mutationKey = ['publishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPost>>, {meetingId: string}> = (props) => {
          const {meetingId} = props ?? {};

          return  publishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPost(meetingId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PublishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPostMutationResult = NonNullable<Awaited<ReturnType<typeof publishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPost>>>
    
    export type PublishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPostMutationError = HTTPValidationError

    /**
 * @summary Publish Minutes To Confluence
 */
export const usePublishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPost>>, TError,{meetingId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPost>>,
        TError,
        {meetingId: string},
        TContext
      > => {
      return useMutation(getPublishMinutesToConfluenceApiV1MinutesMeetingsMeetingIdPublishPostMutationOptions(options), queryClient);
    }
    /**
 * Export meeting minutes in various formats.

Supported formats: markdown, html
 * @summary Export Minutes
 */
export const exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet = (
    meetingId: string,
    params?: ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet200>(
      {url: `/api/v1/minutes/meetings/${meetingId}/minutes/export`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetQueryKey = (meetingId: string,
    params?: ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetParams,) => {
    return [
    `/api/v1/minutes/meetings/${meetingId}/minutes/export`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetQueryOptions = <TData = Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>, TError = HTTPValidationError>(meetingId: string,
    params?: ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetQueryKey(meetingId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>> = ({ signal }) => exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet(meetingId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetQueryResult = NonNullable<Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>>
export type ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetQueryError = HTTPValidationError


export function useExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet<TData = Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params: undefined |  ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet<TData = Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet<TData = Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export Minutes
 */

export function useExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet<TData = Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: ExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportMinutesApiV1MinutesMeetingsMeetingIdMinutesExportGetQueryOptions(meetingId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




