/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListVocabularyApiV1TeamsTeamIdVocabularyGetParams,
  VocabularyBulkImport,
  VocabularyBulkImportResponse,
  VocabularyCreate,
  VocabularyResponse,
  VocabularyUpdate
} from '.././schemas';

import { apiClient } from '../../client';




/**
 * List all vocabulary terms for a team.

Optionally filter by category or search text.
 * @summary List Vocabulary
 */
export const listVocabularyApiV1TeamsTeamIdVocabularyGet = (
    teamId: string,
    params?: ListVocabularyApiV1TeamsTeamIdVocabularyGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<VocabularyResponse[]>(
      {url: `/api/v1/teams/${teamId}/vocabulary`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListVocabularyApiV1TeamsTeamIdVocabularyGetQueryKey = (teamId: string,
    params?: ListVocabularyApiV1TeamsTeamIdVocabularyGetParams,) => {
    return [
    `/api/v1/teams/${teamId}/vocabulary`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListVocabularyApiV1TeamsTeamIdVocabularyGetQueryOptions = <TData = Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>, TError = HTTPValidationError>(teamId: string,
    params?: ListVocabularyApiV1TeamsTeamIdVocabularyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVocabularyApiV1TeamsTeamIdVocabularyGetQueryKey(teamId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>> = ({ signal }) => listVocabularyApiV1TeamsTeamIdVocabularyGet(teamId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVocabularyApiV1TeamsTeamIdVocabularyGetQueryResult = NonNullable<Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>>
export type ListVocabularyApiV1TeamsTeamIdVocabularyGetQueryError = HTTPValidationError


export function useListVocabularyApiV1TeamsTeamIdVocabularyGet<TData = Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>, TError = HTTPValidationError>(
 teamId: string,
    params: undefined |  ListVocabularyApiV1TeamsTeamIdVocabularyGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>,
          TError,
          Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVocabularyApiV1TeamsTeamIdVocabularyGet<TData = Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListVocabularyApiV1TeamsTeamIdVocabularyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>,
          TError,
          Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVocabularyApiV1TeamsTeamIdVocabularyGet<TData = Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListVocabularyApiV1TeamsTeamIdVocabularyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Vocabulary
 */

export function useListVocabularyApiV1TeamsTeamIdVocabularyGet<TData = Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListVocabularyApiV1TeamsTeamIdVocabularyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVocabularyApiV1TeamsTeamIdVocabularyGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVocabularyApiV1TeamsTeamIdVocabularyGetQueryOptions(teamId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Add a new vocabulary term for a team.
 * @summary Create Vocabulary
 */
export const createVocabularyApiV1TeamsTeamIdVocabularyPost = (
    teamId: string,
    vocabularyCreate: VocabularyCreate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<VocabularyResponse>(
      {url: `/api/v1/teams/${teamId}/vocabulary`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: vocabularyCreate, signal
    },
      );
    }
  


export const getCreateVocabularyApiV1TeamsTeamIdVocabularyPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVocabularyApiV1TeamsTeamIdVocabularyPost>>, TError,{teamId: string;data: VocabularyCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createVocabularyApiV1TeamsTeamIdVocabularyPost>>, TError,{teamId: string;data: VocabularyCreate}, TContext> => {

const mutationKey = ['createVocabularyApiV1TeamsTeamIdVocabularyPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createVocabularyApiV1TeamsTeamIdVocabularyPost>>, {teamId: string;data: VocabularyCreate}> = (props) => {
          const {teamId,data} = props ?? {};

          return  createVocabularyApiV1TeamsTeamIdVocabularyPost(teamId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateVocabularyApiV1TeamsTeamIdVocabularyPostMutationResult = NonNullable<Awaited<ReturnType<typeof createVocabularyApiV1TeamsTeamIdVocabularyPost>>>
    export type CreateVocabularyApiV1TeamsTeamIdVocabularyPostMutationBody = VocabularyCreate
    export type CreateVocabularyApiV1TeamsTeamIdVocabularyPostMutationError = HTTPValidationError

    /**
 * @summary Create Vocabulary
 */
export const useCreateVocabularyApiV1TeamsTeamIdVocabularyPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVocabularyApiV1TeamsTeamIdVocabularyPost>>, TError,{teamId: string;data: VocabularyCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createVocabularyApiV1TeamsTeamIdVocabularyPost>>,
        TError,
        {teamId: string;data: VocabularyCreate},
        TContext
      > => {
      return useMutation(getCreateVocabularyApiV1TeamsTeamIdVocabularyPostMutationOptions(options), queryClient);
    }
    /**
 * Get a specific vocabulary term.
 * @summary Get Vocabulary
 */
export const getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet = (
    teamId: string,
    vocabularyId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<VocabularyResponse>(
      {url: `/api/v1/teams/${teamId}/vocabulary/${vocabularyId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGetQueryKey = (teamId: string,
    vocabularyId: string,) => {
    return [
    `/api/v1/teams/${teamId}/vocabulary/${vocabularyId}`
    ] as const;
    }

    
export const getGetVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>, TError = HTTPValidationError>(teamId: string,
    vocabularyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGetQueryKey(teamId,vocabularyId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>> = ({ signal }) => getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet(teamId,vocabularyId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(teamId && vocabularyId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>>
export type GetVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGetQueryError = HTTPValidationError


export function useGetVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet<TData = Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>, TError = HTTPValidationError>(
 teamId: string,
    vocabularyId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>,
          TError,
          Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet<TData = Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>, TError = HTTPValidationError>(
 teamId: string,
    vocabularyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>,
          TError,
          Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet<TData = Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>, TError = HTTPValidationError>(
 teamId: string,
    vocabularyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Vocabulary
 */

export function useGetVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet<TData = Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>, TError = HTTPValidationError>(
 teamId: string,
    vocabularyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdGetQueryOptions(teamId,vocabularyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update a vocabulary term.
 * @summary Update Vocabulary
 */
export const updateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPut = (
    teamId: string,
    vocabularyId: string,
    vocabularyUpdate: VocabularyUpdate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<VocabularyResponse>(
      {url: `/api/v1/teams/${teamId}/vocabulary/${vocabularyId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: vocabularyUpdate, signal
    },
      );
    }
  


export const getUpdateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPut>>, TError,{teamId: string;vocabularyId: string;data: VocabularyUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPut>>, TError,{teamId: string;vocabularyId: string;data: VocabularyUpdate}, TContext> => {

const mutationKey = ['updateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPut>>, {teamId: string;vocabularyId: string;data: VocabularyUpdate}> = (props) => {
          const {teamId,vocabularyId,data} = props ?? {};

          return  updateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPut(teamId,vocabularyId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPut>>>
    export type UpdateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPutMutationBody = VocabularyUpdate
    export type UpdateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Vocabulary
 */
export const useUpdateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPut>>, TError,{teamId: string;vocabularyId: string;data: VocabularyUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPut>>,
        TError,
        {teamId: string;vocabularyId: string;data: VocabularyUpdate},
        TContext
      > => {
      return useMutation(getUpdateVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdPutMutationOptions(options), queryClient);
    }
    /**
 * Delete a vocabulary term.
 * @summary Delete Vocabulary
 */
export const deleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDelete = (
    teamId: string,
    vocabularyId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/teams/${teamId}/vocabulary/${vocabularyId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDelete>>, TError,{teamId: string;vocabularyId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDelete>>, TError,{teamId: string;vocabularyId: string}, TContext> => {

const mutationKey = ['deleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDelete>>, {teamId: string;vocabularyId: string}> = (props) => {
          const {teamId,vocabularyId} = props ?? {};

          return  deleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDelete(teamId,vocabularyId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDelete>>>
    
    export type DeleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Vocabulary
 */
export const useDeleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDelete>>, TError,{teamId: string;vocabularyId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDelete>>,
        TError,
        {teamId: string;vocabularyId: string},
        TContext
      > => {
      return useMutation(getDeleteVocabularyApiV1TeamsTeamIdVocabularyVocabularyIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Bulk import vocabulary terms.

- If skip_duplicates is True (default), existing terms are skipped.
- If skip_duplicates is False, duplicate terms cause a 409 error.
 * @summary Bulk Import Vocabulary
 */
export const bulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPost = (
    teamId: string,
    vocabularyBulkImport: VocabularyBulkImport,
 signal?: AbortSignal
) => {
      
      
      return apiClient<VocabularyBulkImportResponse>(
      {url: `/api/v1/teams/${teamId}/vocabulary/import`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: vocabularyBulkImport, signal
    },
      );
    }
  


export const getBulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPost>>, TError,{teamId: string;data: VocabularyBulkImport}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof bulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPost>>, TError,{teamId: string;data: VocabularyBulkImport}, TContext> => {

const mutationKey = ['bulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPost>>, {teamId: string;data: VocabularyBulkImport}> = (props) => {
          const {teamId,data} = props ?? {};

          return  bulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPost(teamId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type BulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPostMutationResult = NonNullable<Awaited<ReturnType<typeof bulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPost>>>
    export type BulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPostMutationBody = VocabularyBulkImport
    export type BulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPostMutationError = HTTPValidationError

    /**
 * @summary Bulk Import Vocabulary
 */
export const useBulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPost>>, TError,{teamId: string;data: VocabularyBulkImport}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof bulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPost>>,
        TError,
        {teamId: string;data: VocabularyBulkImport},
        TContext
      > => {
      return useMutation(getBulkImportVocabularyApiV1TeamsTeamIdVocabularyImportPostMutationOptions(options), queryClient);
    }
    