"""add_team_filtering_and_confluence_fields

Revision ID: e65c9801a256
Revises: 002
Create Date: 2026-02-03 16:46:05.775636

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e65c9801a256'
down_revision: str | None = '002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('confluence_username', sa.String(length=100), nullable=True))
    op.add_column('teams', sa.Column('confluence_token', sa.String(length=500), nullable=True))
    op.add_column('teams', sa.Column('filtering_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('teams', sa.Column('filtering_confidence_threshold', sa.Float(), nullable=False, server_default='0.7'))
    # Remove server defaults after adding (we have model defaults)
    op.alter_column('teams', 'filtering_enabled', server_default=None)
    op.alter_column('teams', 'filtering_confidence_threshold', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vocabularies', 'category',
               existing_type=sa.Enum('TERMINOLOGY', 'ABBREVIATION', 'NAME', 'OTHER', name='vocabularycategory'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'terminology'::character varying"))
    op.drop_column('teams', 'filtering_confidence_threshold')
    op.drop_column('teams', 'filtering_enabled')
    op.drop_column('teams', 'confluence_token')
    op.drop_column('teams', 'confluence_username')
    # ### end Alembic commands ###
