/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * WeeklyRun API
 * WeeklyRun - AI Meeting Orchestration API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConfluencePageSummary,
  GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet200,
  GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetParams,
  HTTPValidationError,
  ListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetParams,
  WeeklyReportLoadRequest,
  WeeklyReportResponse
} from '.././schemas';

import { apiClient } from '../../client';




/**
 * List available weekly report pages from Confluence.
 * @summary List Weekly Report Pages
 */
export const listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet = (
    params?: ListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ConfluencePageSummary[]>(
      {url: `/api/v1/weekly-reports/confluence/pages`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetQueryKey = (params?: ListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetParams,) => {
    return [
    `/api/v1/weekly-reports/confluence/pages`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetQueryOptions = <TData = Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>, TError = HTTPValidationError>(params?: ListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>> = ({ signal }) => listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>>
export type ListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetQueryError = HTTPValidationError


export function useListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet<TData = Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>, TError = HTTPValidationError>(
 params: undefined |  ListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>,
          TError,
          Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet<TData = Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>, TError = HTTPValidationError>(
 params?: ListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>,
          TError,
          Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet<TData = Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>, TError = HTTPValidationError>(
 params?: ListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Weekly Report Pages
 */

export function useListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet<TData = Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>, TError = HTTPValidationError>(
 params?: ListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListWeeklyReportPagesApiV1WeeklyReportsConfluencePagesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Load and parse a weekly report for a meeting.

Fetches the Confluence page, parses the HTML to extract structured
task data, and stores it associated with the meeting.
 * @summary Load Weekly Report For Meeting
 */
export const loadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPost = (
    meetingId: string,
    weeklyReportLoadRequest: WeeklyReportLoadRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<WeeklyReportResponse>(
      {url: `/api/v1/weekly-reports/meetings/${meetingId}/weekly-report`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: weeklyReportLoadRequest, signal
    },
      );
    }
  


export const getLoadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPost>>, TError,{meetingId: string;data: WeeklyReportLoadRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof loadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPost>>, TError,{meetingId: string;data: WeeklyReportLoadRequest}, TContext> => {

const mutationKey = ['loadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPost>>, {meetingId: string;data: WeeklyReportLoadRequest}> = (props) => {
          const {meetingId,data} = props ?? {};

          return  loadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPost(meetingId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPostMutationResult = NonNullable<Awaited<ReturnType<typeof loadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPost>>>
    export type LoadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPostMutationBody = WeeklyReportLoadRequest
    export type LoadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPostMutationError = HTTPValidationError

    /**
 * @summary Load Weekly Report For Meeting
 */
export const useLoadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPost>>, TError,{meetingId: string;data: WeeklyReportLoadRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPost>>,
        TError,
        {meetingId: string;data: WeeklyReportLoadRequest},
        TContext
      > => {
      return useMutation(getLoadWeeklyReportForMeetingApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportPostMutationOptions(options), queryClient);
    }
    /**
 * Get the weekly report for a meeting.
 * @summary Get Meeting Weekly Report
 */
export const getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet = (
    meetingId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<WeeklyReportResponse>(
      {url: `/api/v1/weekly-reports/meetings/${meetingId}/weekly-report`, method: 'GET', signal
    },
      );
    }
  



export const getGetMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGetQueryKey = (meetingId: string,) => {
    return [
    `/api/v1/weekly-reports/meetings/${meetingId}/weekly-report`
    ] as const;
    }

    
export const getGetMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>, TError = HTTPValidationError>(meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGetQueryKey(meetingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>> = ({ signal }) => getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet(meetingId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>>
export type GetMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGetQueryError = HTTPValidationError


export function useGetMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet<TData = Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>, TError = HTTPValidationError>(
 meetingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet<TData = Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>,
          TError,
          Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet<TData = Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Meeting Weekly Report
 */

export function useGetMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet<TData = Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>, TError = HTTPValidationError>(
 meetingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeetingWeeklyReportApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportGetQueryOptions(meetingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get a text summary of the weekly report for AI context.

Args:
    meeting_id: Meeting ID
    member_name: Optional - get summary for specific member only
 * @summary Get Weekly Report Summary
 */
export const getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet = (
    meetingId: string,
    params?: GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet200>(
      {url: `/api/v1/weekly-reports/meetings/${meetingId}/weekly-report/summary`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetQueryKey = (meetingId: string,
    params?: GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetParams,) => {
    return [
    `/api/v1/weekly-reports/meetings/${meetingId}/weekly-report/summary`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetQueryOptions = <TData = Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>, TError = HTTPValidationError>(meetingId: string,
    params?: GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetQueryKey(meetingId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>> = ({ signal }) => getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet(meetingId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetQueryResult = NonNullable<Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>>
export type GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetQueryError = HTTPValidationError


export function useGetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet<TData = Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params: undefined |  GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet<TData = Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet<TData = Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Weekly Report Summary
 */

export function useGetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet<TData = Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>, TError = HTTPValidationError>(
 meetingId: string,
    params?: GetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWeeklyReportSummaryApiV1WeeklyReportsMeetingsMeetingIdWeeklyReportSummaryGetQueryOptions(meetingId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




